language: python
python:
        - 3.6

install:
        pip install -r requirements.txt
script:
        pytest

services:
        - docker

after_install:
        - docker build -t prodops/flask-app
